### ISSUE TITLE
RazorEngine conflicts with Glimpse?

### ISSUE THREAD

**Issue by impworks** [Antaris/RazorEngine#268]
In my ASP.NET MVC app I have an async controller message that must send an email. The email is processed via RazorEngine. Looks pretty straightforward, but Glimpse seems to conflict with it for some reason.

My code:
```
public virtual async Task<ActionResult> SendEmail()
{
    var path = "~/Views/Email/MyTemplate.cshtml";
    using (var reader = new StreamReader(HostingEnvironment.MapPath(path)))
    {
  	    // fails here:
        var result = Engine.Razor.RunCompile(reader.ReadToEnd(), path, null, new { Id = 1 });
    }
    // ...
}
```

The exception message:
```
Some environments conflict with current Glimpse async support.
Please set Glimpse:DisableAsyncSupport = true in Web.config, or see https://github.com/Glimpse/Glimpse/issues/632 for more details.
```

The exception stacktrace:
```
at Glimpse.AspNet.AspNetFrameworkProvider.AntiSerializationWrapper`1.GetObjectData(SerializationInfo info, StreamingContext context)
at System.Runtime.Serialization.ObjectCloneHelper.GetObjectData(Object serObj, String& typeName, String& assemName, String[]& fieldNames, Object[]& fieldValues)

at System.AppDomain.InternalCreateInstanceFromWithNoSecurity(String assemblyName, String typeName)
at RazorEngine.Compilation.CrossAppDomainCleanUp..ctor(AppDomain toWatch, IPrinter printer)
at RazorEngine.Compilation.CrossAppDomainCleanUp.CreateInitial()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at RazorEngine.Compilation.CrossAppDomainCleanUp.RegisterCleanup(String item, Boolean throwOnDefault)
at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey)
at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
```

Any idea what is wrong? Why is Glimpse implicitly triggered and is there any way RazorEngine can be configured to avoid it?

**Comment by matthid** [comment]
I think this is the same as #267. The workaround should apply here as well. But I have no idea what is going on, do you have a (minimal) repro?

**Comment by matthid** [comment]
I think the solution in https://github.com/Glimpse/Glimpse/issues/632#issuecomment-28994417 might also work for you (ie clearing the HttpContext slot before calling RazorEngine) and re-setting it afterwards.

**Comment by impworks** [comment]
Sorry, the `HttpContext` slot clearing solution didn't work.

**Comment by impworks** [comment]
Update: the problem has been resolved by setting a configuration flag in Glimpse itself, so it's not a RazorEngine issue anymore. Thanks to @matthid for help!

In case anyone stumbles upon the same problem, here's the discussion in Glimpse repository:
Glimpse/Glimpse#896

**Comment by matthid** [comment]
Actually, you can try if https://www.nuget.org/packages/RazorEngine/3.6.5-beta1 fixes the problem as well.
