### ISSUE TITLE
An invalid character was found in the mail header

### ISSUE THREAD

**Issue by dyardyGIT** [Antaris/RazorEngine#276]
Recently, randomly we are getting an exception which i am having a hard time isolating/resolving.  Ideas around why?

I am suspecting some odd characters in the email to address.  Anyone seen this?

---> System.FormatException: An invalid character was found in the mail header: '@'.
at System.Net.Mail.MailAddressParser.ParseLocalPart(String data, Int32& index, Boolean expectAngleBracket, Boolean expectMultipleAddresses)
at System.Net.Mail.MailAddressParser.ParseAddress(String data, Boolean expectMultipleAddresses, Int32& index)
at System.Net.Mail.MailAddressParser.ParseMultipleAddresses(String data)
at System.Net.Mail.MailAddressCollection.ParseValue(String addresses)
at System.Net.Mail.MailAddressCollection.Add(String addresses)

**Comment by matthid** [comment]
From the looks of it this is a problem with anything within the template or in some other code base.
We don't use `System.Net.Mail` anywhere within RazorEngine ... So this is either some sideeffect/bug by the Razor parser or a bug in your code.

Anyway without any repro I'm not sure what to do...

**Comment by andymac4182** [comment]
From what I have read online it appears to be something to do with multiple email addresses when calling the Add method. If you are only passing in a single email address I would guess bad data. 

Eg https://gist.github.com/andymac4182/22e0fd4426ac131b3c87

**Comment by matthid** [comment]
Closing because no further info was provided (regarding RazorEngine).
