### ISSUE TITLE
Type Load Exception when used in web api vnext project

### ISSUE THREAD

**Issue by praveenpamani** [Antaris/RazorEngine#310]
Hi , I am new to Razor, I have a template requirement for which I had successfully got the templates resolved using Razor Engine 4.2.0 - Beta 2 with dependency on Aspnet.Razor (4.0.0-beta4). 

Recently we moved to VS 2015 and i face a Type Load expection as below: 

Additional information: Could not load type 'Microsoft.AspNet.Razor.Generator.GeneratedClassContext' from assembly 'Microsoft.AspNet.Razor, Version=4.0.0.0, Culture=neutral

one observation was  ,when do a nuget of Razor Engine 4.2.0 - beta 2 , i see a dependecy on Aspnet.Razor (4..0.0-Beta6) 

Been a road block for me , appreciate your help

**Comment by matthid** [comment]
> i see a dependecy on Aspnet.Razor (4..0.0-Beta6) 

RazorEngine 4 depends on Razor 4 but was build with beta-1, can you try with that instead (I can try to get a release build against beta-6 but I don't know how much the razor guys changed since last time)

To use Razor3 you need to use RazorEngine 3

**Comment by praveenpamani** [comment]
Hey , I just got the latest , and i saw that dependency has been updated to Beta6 , 

But still the same exception  as below : 

System.TypeLoadException was unhandled by user code
  HResult=-2146233054
  Message=Could not load type 'Microsoft.AspNet.Razor.Generator.GeneratedClassContext' from assembly 'Microsoft.AspNet.Razor, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=RazorEngine
  TypeName=Microsoft.AspNet.Razor.Generator.GeneratedClassContext
  StackTrace:
       at RazorEngine.Compilation.CompilerServiceBase.CreateHost(Type templateType, Type modelType, String className)
       at RazorEngine.Compilation.CompilerServiceBase.GetCodeCompileUnit(TypeContext context)
       at RazorEngine.Compilation.DirectCompilerServiceBase.Compile(TypeContext context)
       at RazorEngine.Compilation.DirectCompilerServiceBase.CompileTypeImpl(TypeContext context)
       at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType_Windows(TypeContext context)
       at RazorEngine.Compilation.DirectCompilerServiceBase.CompileType(TypeContext context)
       at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
       at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
       at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
       at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
       at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
       at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
       at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String templateSource, String name, Type modelType, Object model, DynamicViewBag viewBag)
       at TestWebapi.Controllers.ValuesController.Get(Int32 id) in c:\users\XXXx\documents\visual studio 2015\Projects\TestWorkSpace\src\TestWebapi\Controllers\ValuesController.cs:line 27
  InnerException:

**Comment by matthid** [comment]
What I meant was that you should try to force Aspnet.Razor (4..0.0-Beta1). 

But nevermind, I will upload RazorEngine-4.2.0-beta3 once #311 is green which should work as well.

**Comment by matthid** [comment]
https://www.nuget.org/packages/RazorEngine/4.2.0-beta3 is uploaded.

**Comment by praveenpamani** [comment]
Hola , It worked , Thanks a lot for the quick turn around :+1:
