### ISSUE TITLE
Windows 10 update 1607 - Could not load file or assembly System.Web.Razor

### ISSUE THREAD

**Issue by dalekawamura** [Antaris/RazorEngine#450]
I am running in to issues running on Windows 10 machines with the Anniversary (1607) edition update.  First encountered the issue problem describe here:
https://github.com/Antaris/RazorEngine/issues/416

Corrected that and now get this:
3/2/2017 10:10:52 AM Could not load file or assembly 'System.Web.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
3/2/2017 10:10:52 AM    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()

Source code is pretty basic:
                // Call the Razor Engine to process the file
                var config = new TemplateServiceConfiguration { Debug = true, ReferenceResolver = new MyIReferenceResolver() };
                Engine.Razor = RazorEngineService.Create(config);
                reportHtml = Engine.Razor.RunCompile(File.ReadAllText(reportTemplatePath), "report", null, ReportData);

Has anyone else encountered this?

**Comment by dalekawamura** [comment]
Figured out the problem.  There are 2 different RazorEngine.dll files included with the package, one for 4.0 and one for 4.5.  They are identical in size and report the same version number.  I inadvertently copied the one for 4.0 which was looking from the older System.Web.Razor DLL version.
