### ISSUE TITLE
[4.5.1-alpha001] FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by 0x53A** [Antaris/RazorEngine#485]
After updating to the latest version my call now fails with

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
         File name: 'Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
            at RazorEngine.Roslyn.CSharp.RoslynCompilerServiceBase.CompileType(TypeContext context)
            at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
            at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
            at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
            at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
            at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
            at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
            at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
            at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
            at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
```

I haven't looked too deeply at this, but the only thing that may be missing is a dependency:

![image](https://user-images.githubusercontent.com/4236651/30004692-4b23131c-90d4-11e7-894a-074d3ff3e211.png)

Downgrading to __4.5.0-rc1__ seems to have fixed this, but I haven't started actually verifying it.

**Comment by matthid** [comment]
Sounds reasonable, thanks
