### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.CodeDom, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by pawannogariya** [Antaris/RazorEngine#580]
I am facing this issue when I am calling `RazorEngineService.Compile` method. This is the stack trace
```
   at RazorEngine.Compilation.CSharp.CSharpDirectCompilerService..ctor(Boolean strictMode, Func`1 markupParserFactory)
   at RazorEngine.Compilation.DefaultCompilerServiceFactory.CreateCompilerService(Language language)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.Compile(ITemplateKey key, Type modelType)
   at Swc.EC.LicenseManager.EmailService.EmailBuilders.Razor.RazorService.RegisterTemplate(String templateName, Type viewModelType) in D:\Pawan\Projects\ec-license-manager-api\src\Swc.EC.LicenseManager\Libs\Swc.EC.LicenseManager.EmailService\EmailBuilders\Razor\RazorService.cs:line 54
   at Swc.EC.LicenseManager.EmailService.EmailBuilders.Razor.RazorService.RenderAccountRecoveryEmail(AccountRecoveryEmailViewModel viewModel) in D:\Pawan\Projects\ec-license-manager-api\src\Swc.EC.LicenseManager\Libs\Swc.EC.LicenseManager.EmailService\EmailBuilders\Razor\RazorService.cs:line 28
   at Swc.EC.LicenseManager.EmailService.EmailBuilders.AccountRecoveryEmailBuilder.BuildEmailBody(String recipientFullName, String recoveryUrl) in D:\Pawan\Projects\ec-license-manager-api\src\Swc.EC.LicenseManager\Libs\Swc.EC.LicenseManager.EmailService\EmailBuilders\AccountRecoveryEmailBuilder.cs:line 23
   at Swc.EC.LicenseManager.EmailService.Services.EmailService.SendAccountRecoveryEmail(String email, String recipientFullName, String recoveryKey) in D:\Pawan\Projects\ec-license-manager-api\src\Swc.EC.LicenseManager\Libs\Swc.EC.LicenseManager.EmailService\Services\EmailService.cs:line 60
   at Swc.EC.LicenseManager.WebApi.Controllers.AccountController.ForgotPassword(UserForgotPasswordModel model) in D:\Pawan\Projects\ec-license-manager-api\src\Swc.EC.LicenseManager\Swc.EC.LicenseManager.WebApi\Controllers\AccountController.cs:line 77
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

I tried adding all the dependencies that are listed here https://github.com/Antaris/RazorEngine/blob/master/paket.dependencies
but nothing seems to be working

**Comment by alelom** [comment]
Same issue here. Any tips?

**Comment by 7ayyabzia** [comment]
Any update?

**Comment by tommyw1996** [comment]
Any update on this?
